// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_publicidadRyR;

namespace api_publicidadRyR.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api_publicidadRyR.Entitys.Cliente", b =>
                {
                    b.Property<int>("codigocliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("telefono")
                        .HasColumnType("int");

                    b.HasKey("codigocliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("api_publicidadRyR.Entitys.Detalle_venta", b =>
                {
                    b.Property<int>("id_detalle_venta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("id_prod1")
                        .HasColumnType("int");

                    b.Property<int>("id_ventacodigo_venta")
                        .HasColumnType("int");

                    b.HasKey("id_detalle_venta");

                    b.HasIndex("id_prod1");

                    b.HasIndex("id_ventacodigo_venta");

                    b.ToTable("Detalle_venta");
                });

            modelBuilder.Entity("api_publicidadRyR.Entitys.Juguetes", b =>
                {
                    b.Property<int>("id_prod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cant_prod")
                        .HasColumnType("int");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre_prod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("precio_prod")
                        .HasColumnType("float");

                    b.HasKey("id_prod");

                    b.ToTable("Juguetes");
                });

            modelBuilder.Entity("api_publicidadRyR.Entitys.Usuario", b =>
                {
                    b.Property<int>("codigo_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ape_user")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre_user")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo_user");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("api_publicidadRyR.Entitys.Venta", b =>
                {
                    b.Property<int>("codigo_venta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("codigocliente1")
                        .HasColumnType("int");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("fech_venta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo_venta");

                    b.HasIndex("codigocliente1");

                    b.ToTable("Venta");
                });

            modelBuilder.Entity("api_publicidadRyR.Entitys.Detalle_venta", b =>
                {
                    b.HasOne("api_publicidadRyR.Entitys.Juguetes", "id_prod")
                        .WithMany("detalle_venta")
                        .HasForeignKey("id_prod1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_publicidadRyR.Entitys.Venta", "id_venta")
                        .WithMany("detalle_venta")
                        .HasForeignKey("id_ventacodigo_venta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("id_prod");

                    b.Navigation("id_venta");
                });

            modelBuilder.Entity("api_publicidadRyR.Entitys.Venta", b =>
                {
                    b.HasOne("api_publicidadRyR.Entitys.Cliente", "codigocliente")
                        .WithMany()
                        .HasForeignKey("codigocliente1");

                    b.Navigation("codigocliente");
                });

            modelBuilder.Entity("api_publicidadRyR.Entitys.Juguetes", b =>
                {
                    b.Navigation("detalle_venta");
                });

            modelBuilder.Entity("api_publicidadRyR.Entitys.Venta", b =>
                {
                    b.Navigation("detalle_venta");
                });
#pragma warning restore 612, 618
        }
    }
}
